// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uyozqvwasodxcbibsfnp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV5b3pxdndhc29keGNiaWJzZm5wIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA2OTI4ODAsImV4cCI6MjA2NjI2ODg4MH0.n7vy0HDEBIp-CQt9-jaJkQubTYmV8qZDj7PesDktYN4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);